name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/go-publish.yml@master
    secrets: inherit
    with:
      build-args: -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      cgo-enabled: 1
      project: walletd
